CLASS zcl_lab_04_38_prod_price_53 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA : price TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_04_38_prod_price_53 IMPLEMENTATION.
ENDCLASS.
