CLASS zcl_lab_02_18_lion_53 DEFINITION INHERITING FROM zcl_lab_02_18_animal_53
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS : walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_02_18_lion_53 IMPLEMENTATION.
  METHOD walk.
    rv_cadena = 'El lion walk'.
  ENDMETHOD.

ENDCLASS.
