CLASS zcl_lab_02_23_company_53 DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS ZCL_LAB_02_24_PARTNER_53.
*                 zcl_lab_02_25_collaborator_53.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA : capital TYPE p LENGTH 10 DECIMALS 2 VALUE 999.
ENDCLASS.



CLASS zcl_lab_02_23_company_53 IMPLEMENTATION.
ENDCLASS.
