CLASS zcl_lab_04_51_wz_friend_53 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
*    METHODS : GET_HELPER.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_04_51_wz_friend_53 IMPLEMENTATION.

ENDCLASS.
