CLASS zcl_lab_02_21_classroom_53 DEFINITION
  PUBLIC
*  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_02_21_classroom_53 IMPLEMENTATION.

ENDCLASS.
