CLASS zcl_lab_03_28_logistics DEFINITION INHERITING FROM zcl_lab_03_27_factory_53
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_03_28_logistics IMPLEMENTATION.
ENDCLASS.
