CLASS zcl_lab_02_20_person_53 DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    DATA : name TYPE string.
    METHODS : set_name FINAL IMPORTING iv_name TYPE string.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_02_20_person_53 IMPLEMENTATION.
  METHOD set_name.

  ENDMETHOD.

ENDCLASS.
