CLASS zcl_lab_02_12_linux_053 DEFINITION INHERITING FROM zcl_lab_02_11_system_053
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_02_12_linux_053 IMPLEMENTATION.
ENDCLASS.
